name: CI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['22.x']
    steps:
      - name: Set up something
        shell: bash
        run: |
          echo "Hello World!"
          echo "Running at $(pwd)"
          
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Package VS Code extension
        uses: nhedger/package-vscode-extension@v1
        with:
            extensionPath: $GITHUB_WORKSPACE
            packagePath: ${extensionPath}/Output/v0.2.0-SoberjsVScode.vsix